* a delivery of spiders

2 facts I learned last night:

1. A spider gave birth outside my window.
2. There is a hole into my apartment.

I do not count myself among the people who like spiders. I will not go to their club socials or, if forced, would write on my name tag: "spider coward". Though here, as I write, it occurs that that would be a tremendous mistake. The world is over-stuffed with heroes-at-ready and a spider club's flavor is surely person-itching-to-help-you-overcome-your-fear. 

Last night I held guard for several hours as they trickled in, transgressing the wall nearest the window, climbing to where wall meets ceiling. 8 this hour. 5 this hour. 4 the next. I was there for their first tremulous steps as, presumably, somewhere outside chuffed spider-parents wished they could work a video camera. The invasion was too boring to watch continuously, too frightening to let gain any real depth into my apartment, so I too sleepy to do any real work purchased a game called "American Truck Simulator" and hauled shipments across the American west, taking breaks to check the spider situation every 20 minutes or so.

I got about 30 spiders.
I delivered some potatoes to Nevada I think.

This morning I woke up to the sight of no spiders and it feels like an especially fine day.
